# External Services Configuration
# API keys, URLs, and credentials for third-party services
# Use environment variables for sensitive information in production

# Market Data Providers
market_data:
  polygon:
    api_key: "${POLYGON_API_KEY:-your_polygon_api_key}"
    base_url: "https://api.polygon.io"
    websocket_url: "wss://socket.polygon.io"
    rate_limit: 5  # requests per minute for free tier
    timeout: 30
    
  alpha_vantage:
    api_key: "${ALPHA_VANTAGE_API_KEY:-your_alpha_vantage_key}"
    base_url: "https://www.alphavantage.co"
    rate_limit: 5  # requests per minute for free tier
    timeout: 30
    
  finnhub:
    api_key: "${FINNHUB_API_KEY:-your_finnhub_key}"
    base_url: "https://finnhub.io/api/v1"
    websocket_url: "wss://ws.finnhub.io"
    rate_limit: 60  # requests per minute
    timeout: 30

# News and Alternative Data
news_data:
  benzinga:
    api_key: "${BENZINGA_API_KEY:-your_benzinga_key}"
    base_url: "https://api.benzinga.com"
    rate_limit: 100  # requests per minute
    timeout: 30
    
  news_api:
    api_key: "${NEWS_API_KEY:-your_news_api_key}"
    base_url: "https://newsapi.org/v2"
    rate_limit: 1000  # requests per day for free tier
    timeout: 30

# Fundamental Data
fundamental_data:
  openbb:
    api_key: "${OPENBB_API_KEY:-your_openbb_key}"
    base_url: "https://api.openbb.co"
    rate_limit: 100  # requests per minute
    timeout: 30
    
  sec_edgar:
    base_url: "https://data.sec.gov"
    user_agent: "${SEC_USER_AGENT:-TradingPlatform/1.0 (contact@example.com)}"
    rate_limit: 10  # requests per second
    timeout: 30

# LLM Services
llm_services:
  openai:
    api_key: "${OPENAI_API_KEY:-your_openai_key}"
    base_url: "https://api.openai.com/v1"
    model: "gpt-4"
    max_tokens: 1000
    temperature: 0.1
    timeout: 60
    
  anthropic:
    api_key: "${ANTHROPIC_API_KEY:-your_anthropic_key}"
    base_url: "https://api.anthropic.com"
    model: "claude-3-sonnet-20240229"
    max_tokens: 1000
    temperature: 0.1
    timeout: 60

# Broker APIs
brokers:
  alpaca:
    api_key: "${ALPACA_API_KEY:-your_alpaca_key}"
    secret_key: "${ALPACA_SECRET_KEY:-your_alpaca_secret}"
    base_url: "${ALPACA_BASE_URL:-https://paper-api.alpaca.markets}"  # paper trading
    data_url: "https://data.alpaca.markets"
    websocket_url: "wss://stream.data.alpaca.markets"
    timeout: 30
    
  interactive_brokers:
    host: "${IB_HOST:-localhost}"
    port: "${IB_PORT:-7497}"  # 7497 for TWS, 4001 for Gateway
    client_id: "${IB_CLIENT_ID:-1}"
    timeout: 30

# Message Broker
message_broker:
  kafka:
    bootstrap_servers: "${KAFKA_BOOTSTRAP_SERVERS:-localhost:9092}"
    security_protocol: "${KAFKA_SECURITY_PROTOCOL:-PLAINTEXT}"
    sasl_mechanism: "${KAFKA_SASL_MECHANISM:-PLAIN}"
    sasl_username: "${KAFKA_SASL_USERNAME:-}"
    sasl_password: "${KAFKA_SASL_PASSWORD:-}"
    ssl_cafile: "${KAFKA_SSL_CAFILE:-}"
    ssl_certfile: "${KAFKA_SSL_CERTFILE:-}"
    ssl_keyfile: "${KAFKA_SSL_KEYFILE:-}"
    
  redis:
    host: "${REDIS_HOST:-localhost}"
    port: "${REDIS_PORT:-6379}"
    password: "${REDIS_PASSWORD:-}"
    db: "${REDIS_DB:-0}"

# Monitoring and Alerting
monitoring:
  prometheus:
    host: "${PROMETHEUS_HOST:-localhost}"
    port: "${PROMETHEUS_PORT:-9090}"
    
  grafana:
    host: "${GRAFANA_HOST:-localhost}"
    port: "${GRAFANA_PORT:-3000}"
    username: "${GRAFANA_USERNAME:-admin}"
    password: "${GRAFANA_PASSWORD:-admin}"

# Service-specific settings
service_settings:
  heartbeat_interval: 30  # seconds
  health_check_timeout: 10  # seconds
  max_retry_attempts: 3
  retry_backoff_factor: 2
  circuit_breaker_threshold: 5
  circuit_breaker_timeout: 60  # seconds
